from google import genai 
from google.genai import types   
from pydantic import BaseModel, Field
from src.config.settings import settings
import asyncio
import json

class DocumentVerificationResult(BaseModel):
    """Schema for the OCR audit output generated by Gemini."""
    is_authentic: bool= Field(description= "True if the uploaded image is a valid, authentic PAN or Aadhar card corresponding to the expected type.")
    fields_match: bool= Field(description= "True if both the extracted name and ID number match the expected credentials (with minor spelling/capitalization tolerance allowed).")
    extracted_name: str= Field(description= "The full name read from the card. Use 'unknown' if not legible.")
    extracted_number: str= Field(description= "The card ID number read from the card. Use 'unknown' if not legible.")
    reasoning: str= Field(description= "Brief explanation of the decision, noting matches, mismatches, or quality issues.")

class DocumentVerifierAgent:
    """
    Multimodal AI Agent that reviews verification documents (PAN, Aadhaar)
    using Gemini OCR and validates their authenticity against submitted text.
    """
    def __init__(self) -> None:
        self.client= genai.Client(api_key= settings.GEMINI_API_KEY)
        self.model_name= "gemini-2.0-flash"
        
    def _verify_sync(self, image_bytes: bytes, mime_type: str, doc_type: str, expected_name: str, expected_number: str) -> DocumentVerificationResult:
        prompt= f"""
        You are an expert document verification agent for supplier onboarding.
        Analyze the provided document image and verify it against these expected details:
        
        Expected Document Type: {doc_type} (Must be either 'PAN' or 'Aadhaar')
        Expected Name: '{expected_name}'
        Expected Card Number: '{expected_number}'
        
        Verify the following:
        1. Is this actually an authentic/valid {doc_type} card? (Set is_authentic=false if it's a random image, blank page, or a completely different document).
        2. Extract the Name printed on the card.
        3. Extract the ID Number (PAN or Aadhaar) printed on the card.
        4. Compare the extracted name and number with the Expected Name and Expected Card Number. Allow minor OCR errors or spelling variations.
        
        Provide the output matching the requested schema.
        """
        try:
            response= self.client.models.generate_content(
                model= self.model_name,
                contents= [
                    types.Part.from_bytes(data= image_bytes, mime_type= mime_type),
                    prompt
                ],
                config= types.GenerateContentConfig(
                    response_mime_type= "application/json",
                    response_schema= DocumentVerificationResult,
                    temperature= 0.1
                )
            )
            if response.text:
                return DocumentVerificationResult(**json.loads(response.text))
        except Exception as e:
            print(f"Gemini OCR verification failed: {e}")
        
        # Fallback response in case of API failure
        return DocumentVerificationResult(
            is_authentic= False,
            fields_match= False,
            extracted_name= "unknown",
            extracted_number= "unknown",
            reasoning= f"System error during AI OCR verification: {str(e)}"
        )
    
    async def verify_document(self, image_bytes: bytes, mime_type: str, doc_type: str, expected_name: str, expected_number: str) -> DocumentVerificationResult:
        """Asynchronous execution wrapper to keep FastAPI non-blocking."""
        return await asyncio.to_thread(
            self._verify_sync,
            image_bytes,
            mime_type,
            doc_type,
            expected_name,
            expected_number
        )

document_verifier_agent= DocumentVerifierAgent()