"""Initial schema setup

Revision ID: 32f299c3b539
Revises: 
Create Date: 2026-05-21 11:02:27.166329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f299c3b539'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_pools',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('canonical_product_id', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('target_quantity', sa.Float(), nullable=False),
    sa.Column('current_quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'SOFT_LOCK', 'HARD_LOCK', 'FULFILLED', 'FAILED', name='poolstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_pools_canonical_product_id'), 'order_pools', ['canonical_product_id'], unique=False)
    op.create_index(op.f('ix_order_pools_product_name'), 'order_pools', ['product_name'], unique=False)
    op.create_index(op.f('ix_order_pools_zip_code'), 'order_pools', ['zip_code'], unique=False)
    op.create_table('suppliers',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_table('disputes',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('evidence_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'PENDING_SUPPLIER_RESPONSE', 'UNDER_REVIEW', 'RESOLVED_IN_FAVOR_OF_BUYER', 'RESOLVED_IN_FAVOR_OF_SUPPLIER', 'LOGISTICS_FAULT', name='disputestatus'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='disputeseverity'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('resolution_notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['order_pools.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_restaurant_id'), 'disputes', ['restaurant_id'], unique=False)
    op.create_table('intents',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price_limit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['order_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intents_restaurant_id'), 'intents', ['restaurant_id'], unique=False)
    op.create_table('products',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('moq_threshold', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_intents_restaurant_id'), table_name='intents')
    op.drop_table('intents')
    op.drop_index(op.f('ix_disputes_restaurant_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_order_pools_zip_code'), table_name='order_pools')
    op.drop_index(op.f('ix_order_pools_product_name'), table_name='order_pools')
    op.drop_index(op.f('ix_order_pools_canonical_product_id'), table_name='order_pools')
    op.drop_table('order_pools')
    # ### end Alembic commands ###
