"""add_supplier_verification_fields

Revision ID: b81fe35cf7f7
Revises: 32f299c3b539
Create Date: 2026-05-22 12:27:43.256535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81fe35cf7f7'
down_revision: Union[str, Sequence[str], None] = '32f299c3b539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Create the custom PostgreSQL enum type first
    verification_status_enum = sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus')
    verification_status_enum.create(op.get_bind(), checkfirst=True)

    # 2. Add the columns
    op.add_column('suppliers', sa.Column('pan_number', sa.String(length=10), nullable=True))
    op.add_column('suppliers', sa.Column('aadhar_number', sa.String(length=12), nullable=True))
    op.add_column('suppliers', sa.Column('pan_image_url', sa.String(length=500), nullable=True))
    op.add_column('suppliers', sa.Column('aadhar_image_url', sa.String(length=500), nullable=True))
    op.add_column('suppliers', sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False))
    op.add_column('suppliers', sa.Column('verification_comments', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'verification_comments')
    op.drop_column('suppliers', 'verification_status')
    op.drop_column('suppliers', 'aadhar_image_url')
    op.drop_column('suppliers', 'pan_image_url')
    op.drop_column('suppliers', 'aadhar_number')
    op.drop_column('suppliers', 'pan_number')

    # 3. Clean up the custom PostgreSQL enum type
    verification_status_enum = sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus')
    verification_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###